package com.project.VehicleRentalSystemAPI.mappers;

import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import com.project.VehicleRentalSystemAPI.dto.UserLoginResponseDTO;
import com.project.VehicleRentalSystemAPI.dto.UserRegisterRequestDTO;
import com.project.VehicleRentalSystemAPI.dto.UserRegisterResponseDTO;
import com.project.VehicleRentalSystemAPI.model.entity.Users;

// User mapper to map between Users and UserDTO's
@Mapper(componentModel = "spring")
public interface UserMapper {
    @Mapping(target = "password", ignore = true) // Password will be hashed in service
    @Mapping(target = "id", ignore = true) // ID is generated by DB
    @Mapping(target = "isActive", ignore = true) // Set in service
    Users toUser(UserRegisterRequestDTO userRegisterRequest);

    // Maps User entity to UserRegisterResponseDTO
    UserRegisterResponseDTO toUserRegisterResponseDTO(Users user);

    // The JWT token is not generated by the entity but jwt service
    @Mapping(target = "token", ignore = true)
    UserLoginResponseDTO toUserLoginResponseDTO(Users user);
}