package com.project.VehicleRentalSystemAPI.mappers;

import org.mapstruct.*;

import com.project.VehicleRentalSystemAPI.dto.vehiclecategory.VehicleCategoryRequestDTO;
import com.project.VehicleRentalSystemAPI.dto.vehiclecategory.VehicleCategoryResponseDTO;
import com.project.VehicleRentalSystemAPI.model.entity.VehicleCategory;

@Mapper(componentModel = "spring") // Marks this class as a MapStruct mapper
public interface VehicleCategoryMapper {
    @Mapping(target = "id", ignore = true) // ID is generated by DB for new entities
    VehicleCategory toEntity(VehicleCategoryRequestDTO dto);

    VehicleCategoryResponseDTO toResponseDto(VehicleCategory entity);
}